from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]/'kalz'/'securityx'; ROOT.mkdir(parents=True,exist_ok=True)

def head(title): return ['from __future__ import annotations','','import base64','import hashlib','import json','import secrets','import time','from dataclasses import dataclass, field','from typing import Any, Iterable','','# '+title,'']

def keys():
 names=[f'key_policy_{i:03d}' for i in range(1,321)]
 out=head('Key management, identity keys, rotation, and fingerprints')+['try:','    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey','    from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, PublicFormat, NoEncryption','except ImportError:','    Ed25519PrivateKey = Ed25519PublicKey = None','','class KeyError(RuntimeError): pass','','@dataclass(frozen=True)','class KeyRecord:','    key_id: str','    kind: str','    public_bytes: bytes','    created_at: float','    expires_at: float','    status: str="active"','','class KeyManager:','    def __init__(self): self.records: dict[str,KeyRecord]={}; self.private: dict[str,Any]={}','    def create_signing_key(self, ttl: float=86400.0) -> KeyRecord:','        if Ed25519PrivateKey is None: raise KeyError("cryptography package required")','        key=Ed25519PrivateKey.generate(); public=key.public_key().public_bytes(Encoding.Raw,PublicFormat.Raw); key_id=hashlib.sha256(public).hexdigest()[:32]','        record=KeyRecord(key_id,"ed25519",public,time.time(),time.time()+ttl); self.records[key_id]=record; self.private[key_id]=key; return record','    def sign(self, key_id: str, payload: bytes) -> bytes:','        if key_id not in self.private: raise KeyError("signing key unavailable")','        return self.private[key_id].sign(payload)','    def verify(self, record: KeyRecord, payload: bytes, signature: bytes) -> bool:','        try: Ed25519PublicKey.from_public_bytes(record.public_bytes).verify(signature,payload); return True','        except Exception: return False','    def revoke(self, key_id: str) -> None:','        if key_id not in self.records: raise KeyError("key not found")','        old=self.records[key_id]; self.records[key_id]=KeyRecord(old.key_id,old.kind,old.public_bytes,old.created_at,old.expires_at,"revoked")','    def fingerprint(self, record: KeyRecord) -> str: return hashlib.sha256(record.public_bytes).hexdigest()','','']
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    ttl={3600+i}', '    def policy(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"ttl":self.ttl,"algorithm":"ed25519"}', '    def valid(self, record: KeyRecord, now: float|None=None) -> bool: return record.status=="active" and (now or time.time()) < record.expires_at', '']
 out += ['KEY_POLICIES={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'keys.py').write_text('\n'.join(out)+'\n')

def aead():
 names=[f'encryption_profile_{i:03d}' for i in range(1,321)]
 out=head('AEAD envelope encryption with AES-GCM and authenticated metadata')+['from cryptography.hazmat.primitives.ciphers.aead import AESGCM','','@dataclass(frozen=True)','class EncryptedEnvelope:','    version: int','    key_id: str','    nonce: bytes','    ciphertext: bytes','    aad: bytes','','class EncryptionError(ValueError): pass','','class AEADBox:','    def __init__(self, key: bytes, key_id: str="local"):','        if len(key) not in (16,24,32): raise EncryptionError("AES key must be 128, 192, or 256 bits")','        self.key=key; self.key_id=key_id; self.cipher=AESGCM(key)','    def encrypt(self, plaintext: bytes, aad: bytes=b"") -> EncryptedEnvelope:','        nonce=secrets.token_bytes(12); return EncryptedEnvelope(1,self.key_id,nonce,self.cipher.encrypt(nonce,plaintext,aad),aad)','    def decrypt(self, envelope: EncryptedEnvelope) -> bytes:','        if envelope.key_id != self.key_id: raise EncryptionError("key id mismatch")','        return self.cipher.decrypt(envelope.nonce,envelope.ciphertext,envelope.aad)','    def serialize(self, envelope: EncryptedEnvelope) -> bytes:','        body={"version":envelope.version,"key_id":envelope.key_id,"nonce":base64.b64encode(envelope.nonce).decode(),"ciphertext":base64.b64encode(envelope.ciphertext).decode(),"aad":base64.b64encode(envelope.aad).decode()}; return json.dumps(body,sort_keys=True).encode()','    def digest(self, envelope: EncryptedEnvelope) -> str: return hashlib.sha256(self.serialize(envelope)).hexdigest()','','']
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    aad_prefix={n!r}', '    def aad(self, context: bytes=b"") -> bytes: return self.aad_prefix.encode() + b":" + context', '    def validate(self, envelope: EncryptedEnvelope) -> bool: return envelope.version==1 and bool(envelope.nonce) and bool(envelope.ciphertext)', '    def metadata(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"algorithm":"AES-256-GCM"}', '']
 out += ['ENCRYPTION_PROFILES={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'aead.py').write_text('\n'.join(out)+'\n')

def channel():
 names=[f'channel_policy_{i:03d}' for i in range(1,321)]
 out=head('End-to-end secure channel using X25519, HKDF, and AES-GCM')+['from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey','from cryptography.hazmat.primitives.kdf.hkdf import HKDF','from cryptography.hazmat.primitives import hashes','from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat','','class ChannelError(RuntimeError): pass','','@dataclass(frozen=True)','class SecureMessage:','    sequence: int','    nonce: bytes','    ciphertext: bytes','','class SecureChannel:','    def __init__(self, shared_key: bytes, channel_id: str):','        self.key=HKDF(algorithm=hashes.SHA256(),length=32,salt=None,info=channel_id.encode()).derive(shared_key); self.channel_id=channel_id; self.sequence=0','    @staticmethod','    def keypair() -> tuple[X25519PrivateKey,bytes]:','        private=X25519PrivateKey.generate(); return private,private.public_key().public_bytes(Encoding.Raw,PublicFormat.Raw)','    @staticmethod','    def derive(private: X25519PrivateKey, peer_public: bytes) -> bytes:','        from cryptography.hazmat.primitives.serialization import PublicFormat','        from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PublicKey','        return private.exchange(X25519PublicKey.from_public_bytes(peer_public))','    def send(self, plaintext: bytes, aad: bytes=b"") -> SecureMessage:','        self.sequence += 1; nonce=self.sequence.to_bytes(12,"big"); encrypted=AESGCM(self.key).encrypt(nonce,plaintext,aad); return SecureMessage(self.sequence,nonce,encrypted)','    def receive(self, message: SecureMessage, aad: bytes=b"") -> bytes:','        if message.sequence <= 0: raise ChannelError("invalid sequence")','        return AESGCM(self.key).decrypt(message.nonce,message.ciphertext,aad)','']
 out.insert(3,'from cryptography.hazmat.primitives.ciphers.aead import AESGCM')
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    window={1+i%64}', '    def validate(self, message: SecureMessage) -> bool: return message.sequence > 0 and len(message.nonce)==12 and bool(message.ciphertext)', '    def policy(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"window":self.window,"replay_protection":True}', '']
 out += ['CHANNEL_POLICIES={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'channel.py').write_text('\n'.join(out)+'\n')

def access():
 names=[f'access_policy_{i:03d}' for i in range(1,321)]
 out=head('Capability-based access control, roles, scopes, and audit decisions')+['@dataclass(frozen=True)','class Principal:','    principal_id: str','    roles: frozenset[str]=frozenset()','    capabilities: frozenset[str]=frozenset()','','@dataclass(frozen=True)','class AccessDecision:','    allowed: bool','    principal_id: str','    resource: str','    action: str','    reason: str','','class AccessController:','    def __init__(self): self.roles: dict[str,set[str]]={}; self.audit: list[AccessDecision]=[]','    def grant_role(self, role: str, capabilities: Iterable[str]) -> None: self.roles[role]=set(capabilities)','    def decide(self, principal: Principal, resource: str, action: str) -> AccessDecision:','        granted=set(principal.capabilities)','        for role in principal.roles: granted.update(self.roles.get(role,set()))','        allowed=action in granted or f"{resource}:{action}" in granted','        decision=AccessDecision(allowed,principal.principal_id,resource,action,"capability matched" if allowed else "capability missing"); self.audit.append(decision); return decision','    def enforce(self, principal: Principal, resource: str, action: str) -> None:','        if not self.decide(principal,resource,action).allowed: raise PermissionError("access denied")','    def report(self) -> dict[str,Any]: return {"decisions":len(self.audit),"allowed":sum(item.allowed for item in self.audit)}','','']
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    default_scope="scope:{i%16}"', '    def allows(self, principal: Principal, action: str) -> bool: return action in principal.capabilities or self.default_scope in principal.capabilities', '    def metadata(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"default_scope":self.default_scope}', '']
 out += ['ACCESS_POLICIES={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'access.py').write_text('\n'.join(out)+'\n')

def secretsx():
 names=[f'secret_policy_{i:03d}' for i in range(1,321)]
 out=head('Secret storage, envelope keys, rotation, expiry, and redaction')+['@dataclass(frozen=True)','class SecretVersion:','    name: str','    version: int','    ciphertext: bytes','    created_at: float','    expires_at: float','','class SecretStore:','    def __init__(self, box: Any): self.box=box; self.items: dict[str,list[SecretVersion]]={}','    def put(self, name: str, plaintext: bytes, ttl: float=86400.0) -> SecretVersion:','        version=len(self.items.get(name,[]))+1; envelope=self.box.encrypt(plaintext,name.encode()); item=SecretVersion(name,version,self.box.serialize(envelope),time.time(),time.time()+ttl); self.items.setdefault(name,[]).append(item); return item','    def get(self, name: str, version: int|None=None) -> bytes:','        versions=self.items.get(name,[]); selected=versions[(version or len(versions))-1] if versions else None','        if selected is None or selected.expires_at <= time.time(): raise KeyError("secret unavailable")','        from .aead import EncryptedEnvelope','        body=json.loads(selected.ciphertext); envelope=EncryptedEnvelope(body["version"],body["key_id"],base64.b64decode(body["nonce"]),base64.b64decode(body["ciphertext"]),base64.b64decode(body["aad"])); return self.box.decrypt(envelope)','    def rotate(self, name: str, plaintext: bytes) -> SecretVersion: return self.put(name,plaintext)','    def metadata(self) -> dict[str,Any]: return {name:len(values) for name,values in self.items.items()}','','']
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    ttl={3600+i}', '    def valid(self, secret: SecretVersion, now: float|None=None) -> bool: return secret.expires_at > (now or time.time())', '    def redact(self, value: bytes) -> str: return hashlib.sha256(value).hexdigest()[:16]', '    def policy(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"ttl":self.ttl,"rotation":True}', '']
 out += ['SECRET_POLICIES={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'secrets.py').write_text('\n'.join(out)+'\n')

if __name__=='__main__': keys(); aead(); channel(); access(); secretsx()
