from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]/'kalz'/'distributed'
ROOT.mkdir(parents=True,exist_ok=True)

def common(title):
 return ['from __future__ import annotations','','import asyncio','import hashlib','import json','import time','from dataclasses import dataclass, field','from typing import Any, Callable, Iterable','','f"""{title}"""','']

def emit_partition():
 names=[f'partition_strategy_{i:03d}' for i in range(1,321)]
 out=common('Distributed partitioning and data locality engine')+['@dataclass(frozen=True)','class Record:','    key: str','    value: Any','    timestamp: float = 0.0','    metadata: dict[str,Any] = field(default_factory=dict)','','@dataclass(frozen=True)','class Partition:','    partition_id: int','    records: tuple[Record,...]','    checksum: str','','class PartitionError(ValueError): pass','','class Partitioner:','    def __init__(self, count: int):','        if count < 1: raise PartitionError("partition count must be positive")','        self.count=count','    def assign(self, record: Record) -> int:','        return int(hashlib.sha256(record.key.encode()).hexdigest(),16) % self.count','    def split(self, records: Iterable[Record]) -> tuple[Partition,...]:','        buckets=[[] for _ in range(self.count)]','        for record in records: buckets[self.assign(record)].append(record)','        return tuple(Partition(i,tuple(bucket),self.checksum(bucket)) for i,bucket in enumerate(buckets))','    def checksum(self, records: Iterable[Record]) -> str:','        body=json.dumps([record.__dict__ for record in records],sort_keys=True,default=str).encode()','        return hashlib.sha256(body).hexdigest()','    def rebalance(self, partitions: Iterable[Partition], count: int) -> tuple[Partition,...]:','        return Partitioner(count).split(record for partition in partitions for record in partition.records)','']
 for i,n in enumerate(names,1):
  cls=''.join(x.title() for x in n.split('_'))
  out += [f'class {cls}(Partitioner):',f'    name={n!r}',f'    sequence={i}','    def assign(self, record: Record) -> int:',f'        return (super().assign(record)+{i}) % self.count','    def score(self, partition: Partition) -> float:',f'        return len(partition.records) / max(1,self.count) + {i}/1000','']
 out += ['PARTITION_STRATEGIES={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(1),' for n in names],'}','']
 (ROOT/'partition.py').write_text('\n'.join(out)+'\n')

def emit_shuffle():
 names=[f'shuffle_operator_{i:03d}' for i in range(1,321)]
 out=common('Distributed shuffle, grouping, sorting, and aggregation engine')+['@dataclass(frozen=True)','class ShuffleBatch:','    batch_id: str','    records: tuple[Record,...]','    partition_id: int','','class ShuffleError(RuntimeError): pass','','class ShuffleOperator:','    name="base"','    def map(self, record: Record) -> tuple[str,Any]: return record.key,record.value','    def reduce(self, key: str, values: list[Any]) -> Any: return values[-1] if values else None','    def shuffle(self, records: Iterable[Record]) -> dict[str,list[Any]]:','        grouped: dict[str,list[Any]]={}','        for record in records:','            key,value=self.map(record); grouped.setdefault(key,[]).append(value)','        return grouped','    def aggregate(self, records: Iterable[Record]) -> tuple[Record,...]:','        return tuple(Record(key,str(self.reduce(key,values)),time.time()) for key,values in self.shuffle(records).items())','','']
 for i,n in enumerate(names,1):
  cls=''.join(x.title() for x in n.split('_'))
  out += [f'class {cls}(ShuffleOperator):',f'    name={n!r}',f'    sequence={i}','    def map(self, record: Record) -> tuple[str,Any]:',f'        return f"{i}:{{record.key}}", record.value','    def reduce(self, key: str, values: list[Any]) -> Any:',f'        return {{"operator": self.name, "count": len(values), "values": values[-{1 if i%3 else 3}:]}}','    def validate(self, batch: ShuffleBatch) -> bool:',f'        return batch.partition_id >= 0 and bool(batch.batch_id) and {str(i%2==0)}','']
 out += ['SHUFFLE_OPERATORS={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'() ,' for n in names],'}','']
 (ROOT/'shuffle.py').write_text('\n'.join(out)+'\n')

def emit_workers():
 names=[f'worker_capability_{i:03d}' for i in range(1,321)]
 out=common('Worker pool, task leasing, backpressure, and retry engine')+['@dataclass(frozen=True)','class Task:','    task_id: str','    payload: Any','    attempt: int=0','','@dataclass(frozen=True)','class TaskResult:','    task_id: str','    status: str','    value: Any=None','    error: str=""','','class WorkerError(RuntimeError): pass','','class WorkerPool:','    def __init__(self, size: int=4, max_queue: int=100):','        if size<1 or max_queue<1: raise WorkerError("invalid worker configuration")','        self.size=size; self.queue: asyncio.Queue[Task]=asyncio.Queue(maxsize=max_queue); self.results: dict[str,TaskResult]={}; self.running=False','    async def submit(self, task: Task) -> None: await self.queue.put(task)','    async def run_task(self, task: Task, handler: Callable[[Any],Any], retries: int=2) -> TaskResult:','        for attempt in range(retries+1):','            try:','                value=handler(task.payload)','                result=TaskResult(task.task_id,"completed",value)','                self.results[task.task_id]=result; return result','            except Exception as error:','                if attempt>=retries:','                    result=TaskResult(task.task_id,"failed",error=str(error)); self.results[task.task_id]=result; return result','        raise WorkerError("unreachable")','    async def drain(self, handler: Callable[[Any],Any], retries: int=2) -> list[TaskResult]:','        results=[]','        while not self.queue.empty(): results.append(await self.run_task(await self.queue.get(),handler,retries))','        return results','    def health(self) -> dict[str,Any]: return {"queued":self.queue.qsize(),"results":len(self.results),"running":self.running}','']
 for i,n in enumerate(names,1):
  cls=''.join(x.title() for x in n.split('_'))
  out += [f'class {cls}:',f'    name={n!r}',f'    sequence={i}',f'    concurrency={1+(i%8)}','    def capacity(self) -> int: return self.concurrency * max(1, self.sequence % 16)','    def accepts(self, task: Task) -> bool: return bool(task.task_id and task.attempt >= 0)','    def routing_key(self, task: Task) -> str: return f"{self.name}:{task.task_id}"','']
 out += ['WORKER_CAPABILITIES={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'() ,' for n in names],'}','']
 (ROOT/'workers.py').write_text('\n'.join(out)+'\n')

def emit_checkpoint():
 names=[f'checkpoint_policy_{i:03d}' for i in range(1,321)]
 out=common('Checkpoint, recovery, exactly-once markers, and data lineage')+['@dataclass(frozen=True)','class Checkpoint:','    checkpoint_id: str','    stage: str','    offsets: tuple[tuple[str,int],...]','    checksum: str','','class CheckpointError(RuntimeError): pass','','class CheckpointStore:','    def __init__(self): self.items: dict[str,Checkpoint]={}','    def save(self, checkpoint: Checkpoint) -> Checkpoint:','        if not checkpoint.checkpoint_id: raise CheckpointError("checkpoint id required")','        self.items[checkpoint.checkpoint_id]=checkpoint; return checkpoint','    def load(self, checkpoint_id: str) -> Checkpoint:','        if checkpoint_id not in self.items: raise CheckpointError("checkpoint not found")','        return self.items[checkpoint_id]','    def verify(self, checkpoint: Checkpoint) -> bool:','        body=json.dumps({"id":checkpoint.checkpoint_id,"stage":checkpoint.stage,"offsets":checkpoint.offsets},sort_keys=True).encode()','        return hashlib.sha256(body).hexdigest()==checkpoint.checksum','    def latest(self, stage: str) -> Checkpoint|None:','        values=[item for item in self.items.values() if item.stage==stage]','        return values[-1] if values else None','']
 for i,n in enumerate(names,1):
  cls=''.join(x.title() for x in n.split('_'))
  out += [f'class {cls}:',f'    name={n!r}',f'    sequence={i}',f'    retention={1+(i%30)}','    def eligible(self, offsets: dict[str,int]) -> bool: return all(value >= 0 for value in offsets.values())','    def lineage(self, stage: str, offsets: dict[str,int]) -> dict[str,Any]: return {"policy":self.name,"stage":stage,"offsets":dict(sorted(offsets.items())),"retention":self.retention}','']
 out += ['CHECKPOINT_POLICIES={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'() ,' for n in names],'}','']
 (ROOT/'checkpoint.py').write_text('\n'.join(out)+'\n')

def emit_pipeline():
 names=[f'distributed_stage_{i:03d}' for i in range(1,321)]
 out=common('Distributed data pipeline coordinator and fault recovery')+['@dataclass(frozen=True)','class Stage:','    name: str','    inputs: tuple[str,...]=()','    outputs: tuple[str,...]=()','','@dataclass(frozen=True)','class PipelineReport:','    pipeline_id: str','    status: str','    stages: tuple[str,...]','    failures: tuple[str,...]=()','','class PipelineError(RuntimeError): pass','','class DistributedPipeline:','    def __init__(self, pipeline_id: str): self.pipeline_id=pipeline_id; self.stages: dict[str,Stage]={}; self.reports=[]','    def add(self, stage: Stage) -> None:','        if stage.name in self.stages: raise PipelineError("duplicate stage")','        self.stages[stage.name]=stage','    def order(self) -> tuple[str,...]:','        pending=dict(self.stages); resolved=[]','        while pending:','            ready=[name for name,stage in pending.items() if all(dep in resolved for dep in stage.inputs)]','            if not ready: raise PipelineError("stage dependency cycle")','            for name in sorted(ready): resolved.append(name); pending.pop(name)','        return tuple(resolved)','    def plan(self) -> PipelineReport:','        result=PipelineReport(self.pipeline_id,"planned",self.order()); self.reports.append(result); return result','    def recover(self, failed_stage: str) -> PipelineReport:','        order=self.order(); failures=tuple(name for name in order if name==failed_stage or order.index(name)>order.index(failed_stage))','        result=PipelineReport(self.pipeline_id,"recovery-planned",order,failures); self.reports.append(result); return result','    def metrics(self) -> dict[str,Any]: return {"stages":len(self.stages),"reports":len(self.reports)}','']
 for i,n in enumerate(names,1):
  cls=''.join(x.title() for x in n.split('_'))
  dep=f'distributed_stage_{i-1:03d}' if i>1 else ''
  out += [f'class {cls}:',f'    name={n!r}',f'    sequence={i}',f'    input_stage={dep!r}', '    def stage(self) -> Stage:',f'        return Stage(self.name,(self.input_stage,) if self.input_stage else (), (f"{{self.name}}:output",))','    def watermark(self, timestamp: float) -> float: return max(0.0,timestamp)','    def fingerprint(self) -> str: return hashlib.sha256(self.name.encode()).hexdigest()','']
 out += ['DISTRIBUTED_STAGES=[',*['    '+''.join(x.title() for x in n.split('_'))+'().stage(),' for n in names],']','', 'def build_pipeline(pipeline_id: str="default") -> DistributedPipeline:', '    pipeline=DistributedPipeline(pipeline_id)', '    for stage in DISTRIBUTED_STAGES: pipeline.add(stage)', '    return pipeline','']
 (ROOT/'pipeline.py').write_text('\n'.join(out)+'\n')

if __name__=='__main__': emit_partition(); emit_shuffle(); emit_workers(); emit_checkpoint(); emit_pipeline()
