from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]/'kalz'/'observability'; ROOT.mkdir(parents=True,exist_ok=True)

def head(title): return ['from __future__ import annotations','','import hashlib','import json','import queue','import threading','import time','from dataclasses import dataclass, field','from typing import Any, Iterable','','# '+title,'']

def metrics():
 names=[f'metric_definition_{i:03d}' for i in range(1,321)]
 out=head('Real-time metrics collection and rolling aggregation')+['@dataclass(frozen=True)','class Sample:','    name: str','    value: float','    timestamp: float','    labels: tuple[tuple[str,str],...]=()','','class MetricError(ValueError): pass','','class MetricsStore:','    def __init__(self, max_samples: int=10000): self.max_samples=max_samples; self.samples: list[Sample]=[]; self.lock=threading.RLock()','    def record(self, name: str, value: float, labels: dict[str,str]|None=None) -> Sample:','        if not name: raise MetricError("metric name required")','        sample=Sample(name,float(value),time.time(),tuple(sorted((labels or {}).items())))','        with self.lock: self.samples.append(sample); self.samples=self.samples[-self.max_samples:]','        return sample','    def query(self, name: str|None=None, since: float=0.0) -> tuple[Sample,...]:','        with self.lock: return tuple(item for item in self.samples if (name is None or item.name==name) and item.timestamp>=since)','    def aggregate(self, name: str) -> dict[str,float]:','        values=[item.value for item in self.query(name)]','        return {"count":len(values),"min":min(values,default=0.0),"max":max(values,default=0.0),"avg":sum(values)/len(values) if values else 0.0}','']
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    unit={"count" if i%3==0 else "seconds" if i%3==1 else "bytes"!r}', '    def emit(self, store: MetricsStore, value: float=0.0, labels: dict[str,str]|None=None) -> Sample: return store.record(self.name,value,labels)', '    def descriptor(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"unit":self.unit}', '']
 out += ['METRIC_DEFINITIONS={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'metrics.py').write_text('\n'.join(out)+'\n')

def logs():
 names=[f'log_schema_{i:03d}' for i in range(1,321)]
 out=head('Distributed structured logging with ingestion, redaction, and ordering')+['@dataclass(frozen=True)','class LogEvent:','    event_id: str','    level: str','    message: str','    service: str','    timestamp: float','    trace_id: str=""','    fields: dict[str,Any]=field(default_factory=dict)','','class LogError(ValueError): pass','','class DistributedLogStore:','    def __init__(self, capacity: int=10000): self.capacity=capacity; self.events: list[LogEvent]=[]; self.lock=threading.RLock()','    def append(self, event: LogEvent) -> None:','        if event.level not in {"debug","info","warning","error","critical"}: raise LogError("invalid level")','        with self.lock: self.events.append(event); self.events=self.events[-self.capacity:]','    def query(self, level: str|None=None, trace_id: str|None=None) -> tuple[LogEvent,...]:','        with self.lock: return tuple(item for item in self.events if (level is None or item.level==level) and (trace_id is None or item.trace_id==trace_id))','    def redact(self, event: LogEvent, fields: Iterable[str]) -> LogEvent:','        hidden=dict(event.fields)','        for field_name in fields:','            if field_name in hidden: hidden[field_name]="[REDACTED]"','        return LogEvent(event.event_id,event.level,event.message,event.service,event.timestamp,event.trace_id,hidden)','    def export(self) -> list[dict[str,Any]]: return [item.__dict__ for item in self.query()]','','']
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    default_level={"info" if i%4 else "warning"!r}', '    def valid(self, event: LogEvent) -> bool: return bool(event.event_id and event.service and event.message)', '    def schema(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"level":self.default_level}', '']
 out += ['LOG_SCHEMAS={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'logging.py').write_text('\n'.join(out)+'\n')

def tracing():
 names=[f'trace_sampler_{i:03d}' for i in range(1,321)]
 out=head('Distributed tracing spans, context propagation, and service graphs')+['@dataclass(frozen=True)','class Span:','    trace_id: str','    span_id: str','    parent_id: str|None','    operation: str','    start: float','    end: float','    attributes: dict[str,Any]=field(default_factory=dict)','','class TraceStore:','    def __init__(self): self.spans: dict[str,Span]={}; self.lock=threading.RLock()','    def start(self, operation: str, trace_id: str|None=None, parent_id: str|None=None) -> Span:','        now=time.time(); trace_id=trace_id or hashlib.sha256(f"{now}:{operation}".encode()).hexdigest()[:32]; span_id=hashlib.sha256(f"{trace_id}:{now}".encode()).hexdigest()[:16]','        span=Span(trace_id,span_id,parent_id,operation,now,now); self.spans[span_id]=span; return span','    def finish(self, span: Span, attributes: dict[str,Any]|None=None) -> Span:','        completed=Span(span.trace_id,span.span_id,span.parent_id,span.operation,span.start,time.time(),attributes or span.attributes); self.spans[span.span_id]=completed; return completed','    def trace(self, trace_id: str) -> tuple[Span,...]: return tuple(item for item in self.spans.values() if item.trace_id==trace_id)','    def duration(self, span: Span) -> float: return max(0.0,span.end-span.start)','','']
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    rate={(i%100+1)/100}', '    def sample(self, value: int) -> bool: return (value % 100) < int(self.rate*100)', '    def metadata(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"rate":self.rate}', '']
 out += ['TRACE_SAMPLERS={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'tracing.py').write_text('\n'.join(out)+'\n')

def alerts():
 names=[f'alert_rule_{i:03d}' for i in range(1,321)]
 out=head('Real-time alerting, thresholds, incidents, and suppression')+['@dataclass(frozen=True)','class Alert:','    rule: str','    severity: str','    message: str','    value: float','    threshold: float','    timestamp: float','    resolved: bool=False','','class AlertEngine:','    def __init__(self): self.rules: dict[str,AlertRule]={}; self.alerts: list[Alert]=[]','    def register(self, rule: "AlertRule") -> None: self.rules[rule.name]=rule','    def evaluate(self, name: str, value: float) -> Alert|None:','        rule=self.rules[name]; triggered=rule.trigger(value)','        alert=Alert(name,rule.severity,rule.message,value,rule.threshold,time.time(),not triggered)','        if triggered: self.alerts.append(alert)','        return alert if triggered else None','    def active(self) -> tuple[Alert,...]: return tuple(item for item in self.alerts if not item.resolved)','    def resolve(self, name: str) -> int:','        count=0; updated=[]','        for item in self.alerts:','            if item.rule==name and not item.resolved: updated.append(Alert(item.rule,item.severity,item.message,item.value,item.threshold,item.timestamp,True)); count+=1','            else: updated.append(item)','        self.alerts=updated; return count','','@dataclass(frozen=True)','class AlertRule:','    name: str','    threshold: float','    severity: str="warning"','    message: str="threshold exceeded"','    direction: str="above"','    def trigger(self, value: float) -> bool: return value >= self.threshold if self.direction=="above" else value <= self.threshold','','']
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    severity={"critical" if i%20==0 else "warning"!r}',f'    threshold={i/10}', '    def rule(self) -> AlertRule: return AlertRule(self.name,self.threshold,self.severity,f"{self.name} triggered")', '    def metadata(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"severity":self.severity}', '']
 out += ['ALERT_RULES={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'alerts.py').write_text('\n'.join(out)+'\n')

def export():
 names=[f'export_format_{i:03d}' for i in range(1,321)]
 out=head('Observability export, retention, batching, and distributed sinks')+['@dataclass(frozen=True)','class ExportBatch:','    batch_id: str','    records: tuple[dict[str,Any],...]','    created_at: float','    checksum: str','','class Exporter:','    def __init__(self): self.batches: list[ExportBatch]=[]','    def batch(self, records: Iterable[dict[str,Any]], batch_id: str) -> ExportBatch:','        items=tuple(records); checksum=hashlib.sha256(json.dumps(items,sort_keys=True,default=str).encode()).hexdigest(); result=ExportBatch(batch_id,items,time.time(),checksum); self.batches.append(result); return result','    def verify(self, batch: ExportBatch) -> bool: return hashlib.sha256(json.dumps(batch.records,sort_keys=True,default=str).encode()).hexdigest()==batch.checksum','    def retention(self, before: float) -> int:','        old=len(self.batches); self.batches=[item for item in self.batches if item.created_at>=before]; return old-len(self.batches)','    def report(self) -> dict[str,Any]: return {"batches":len(self.batches),"records":sum(len(item.records) for item in self.batches)}','','']
 for i,n in enumerate(names,1):
  c=''.join(x.title() for x in n.split('_'))
  out += [f'class {c}:',f'    name={n!r}',f'    sequence={i}',f'    compression={"json" if i%2 else "ndjson"!r}', '    def encode(self, records: Iterable[dict[str,Any]]) -> bytes: return json.dumps(list(records),sort_keys=True,default=str).encode()', '    def descriptor(self) -> dict[str,Any]: return {"name":self.name,"sequence":self.sequence,"compression":self.compression}', '']
 out += ['EXPORT_FORMATS={',*['    '+repr(n)+': '+''.join(x.title() for x in n.split('_'))+'(),' for n in names],'}','']
 (ROOT/'export.py').write_text('\n'.join(out)+'\n')

if __name__=='__main__': metrics(); logs(); tracing(); alerts(); export()
