from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / 'kalz'

def make_automation() -> None:
    categories = {
        'distro': ['read_os_release', 'detect_kernel', 'detect_architecture', 'detect_init', 'detect_container', 'detect_virtualization', 'detect_cpu', 'detect_memory', 'detect_gpu', 'detect_secure_boot', 'detect_display_server', 'detect_locale', 'detect_timezone', 'detect_hostname', 'detect_users', 'detect_groups', 'detect_mounts', 'detect_network', 'detect_dns', 'detect_firewall'],
        'package': ['refresh_indexes', 'resolve_package', 'plan_install', 'plan_remove', 'plan_upgrade', 'plan_repair', 'verify_package', 'list_orphans', 'detect_sources', 'validate_sources', 'snapshot_packages', 'restore_packages', 'compare_packages', 'export_manifest', 'import_manifest', 'check_locks', 'check_signatures', 'check_disk_space', 'check_cache', 'clean_cache'],
        'config': ['load_yaml', 'load_json', 'load_toml', 'merge_layers', 'validate_schema', 'write_user_config', 'write_system_config', 'backup_config', 'restore_config', 'diff_config', 'normalize_config', 'redact_config', 'rotate_config', 'lock_config', 'unlock_config', 'check_permissions', 'check_ownership', 'check_syntax', 'apply_template', 'render_report'],
        'health': ['check_service', 'check_socket', 'check_port', 'check_process', 'check_disk', 'check_inode', 'check_memory', 'check_cpu', 'check_temperature', 'check_kernel_logs', 'check_journal', 'check_updates', 'check_time_sync', 'check_dns', 'check_routes', 'check_mount', 'check_permissions', 'check_certificates', 'check_backups', 'check_audit_chain'],
        'desktop': ['detect_kde', 'detect_xfce', 'detect_gnome', 'detect_cinnamon', 'detect_mate', 'detect_lxqt', 'detect_sway', 'detect_i3', 'detect_hyprland', 'detect_budgie', 'apply_qss_theme', 'apply_qml_theme', 'install_desktop_entry', 'install_mime_handler', 'configure_notifications', 'configure_shortcuts', 'configure_panel', 'configure_terminal', 'configure_file_manager', 'export_desktop_profile'],
        'backup': ['create_snapshot', 'verify_snapshot', 'restore_snapshot', 'rotate_snapshots', 'prune_snapshots', 'export_archive', 'import_archive', 'hash_archive', 'encrypt_archive', 'decrypt_archive', 'check_retention', 'check_capacity', 'backup_database', 'backup_audit', 'backup_plugins', 'backup_themes', 'backup_scopes', 'backup_reports', 'backup_workflows', 'backup_scheduler'],
        'report': ['collect_inventory', 'collect_health', 'collect_jobs', 'collect_audit', 'collect_scopes', 'collect_tools', 'collect_plugins', 'collect_backups', 'render_json', 'render_markdown', 'render_html', 'render_csv', 'render_xml', 'render_pdf_plan', 'compare_reports', 'sign_report', 'verify_report', 'redact_report', 'archive_report', 'publish_report'],
        'workflow': ['validate_workflow', 'expand_workflow', 'plan_workflow', 'run_workflow', 'pause_workflow', 'resume_workflow', 'stop_workflow', 'retry_workflow', 'rollback_workflow', 'clone_workflow', 'export_workflow', 'import_workflow', 'schedule_workflow', 'unschedule_workflow', 'tag_workflow', 'audit_workflow', 'diff_workflow', 'lint_workflow', 'test_workflow', 'summarize_workflow'],
    }
    ops = [(cat, name) for cat, names in categories.items() for name in names]
    out = ['from __future__ import annotations', '', 'import hashlib', 'import json', 'import time', 'from dataclasses import dataclass, field', 'from typing import Any', '', '@dataclass(frozen=True)', 'class OperationContext:', '    operation_id: str', '    mode: str = "safe"', '    dry_run: bool = True', '    actor: str = "system"', '    scope: tuple[str, ...] = ()', '    metadata: dict[str, Any] = field(default_factory=dict)', '', '@dataclass(frozen=True)', 'class OperationResult:', '    operation_id: str', '    category: str', '    name: str', '    status: str', '    changed: bool', '    details: dict[str, Any]', '', 'class AutomationError(RuntimeError): pass', '', 'class AutomationOperation:', '    category = "generic"', '    name = "operation"', '    reversible = True', '    requires_privilege = False', '    def validate(self, context: OperationContext) -> None:', '        if not context.operation_id.strip(): raise AutomationError("operation_id is required")', '        if context.mode not in {"safe", "standard", "advanced", "lab"}: raise AutomationError("invalid mode")', '    def plan(self, context: OperationContext) -> dict[str, Any]:', '        self.validate(context)', '        return {"operation_id": context.operation_id, "category": self.category, "name": self.name, "dry_run": context.dry_run, "reversible": self.reversible, "requires_privilege": self.requires_privilege}', '    def execute(self, context: OperationContext) -> OperationResult:', '        plan = self.plan(context)', '        changed = not context.dry_run', '        return OperationResult(context.operation_id, self.category, self.name, "planned" if context.dry_run else "completed", changed, plan)', '    def rollback(self, context: OperationContext) -> OperationResult:', '        self.validate(context)', '        return OperationResult(context.operation_id, self.category, self.name, "rolled_back", False, {"reason": "explicit rollback"})', '    def fingerprint(self, context: OperationContext) -> str:', '        return hashlib.sha256(json.dumps(self.plan(context), sort_keys=True).encode()).hexdigest()', '']
    for idx, (cat, name) in enumerate(ops):
        cls = ''.join(part.title() for part in name.split('_')) + 'Operation'
        out += [f'class {cls}(AutomationOperation):', f'    category = {cat!r}', f'    name = {name!r}', f'    reversible = {str(idx % 11 != 0)}', f'    requires_privilege = {str(cat in {"package", "config", "desktop"} and idx % 3 == 0)}', '    def validate(self, context: OperationContext) -> None:', '        super().validate(context)', f'        if context.mode == "safe" and {str(cat in {"package", "config", "desktop"})} and not context.dry_run:', '            raise AutomationError("safe mode requires dry_run for privileged operation")', '    def plan(self, context: OperationContext) -> dict[str, Any]:', '        plan = super().plan(context)', f'        plan.update({{"sequence": {idx}, "risk": {"high" if idx % 7 == 0 else "medium" if idx % 3 == 0 else "low"!r}}})', '        return plan', '']
    out += ['OPERATIONS: dict[str, AutomationOperation] = {}', '']
    for cat, name in ops:
        cls = ''.join(part.title() for part in name.split('_')) + 'Operation'
        out += [f'OPERATIONS[{name!r}] = {cls}()', '']
    out += ['class AutomationEngine:', '    def __init__(self) -> None:', '        self.operations = dict(OPERATIONS)', '        self.history: list[OperationResult] = []', '    def register(self, operation: AutomationOperation) -> None:', '        if operation.name in self.operations: raise AutomationError("duplicate operation")', '        self.operations[operation.name] = operation', '    def plan(self, name: str, context: OperationContext) -> dict[str, Any]:', '        if name not in self.operations: raise AutomationError(f"unknown operation: {name}")', '        return self.operations[name].plan(context)', '    def execute(self, name: str, context: OperationContext) -> OperationResult:', '        if name not in self.operations: raise AutomationError(f"unknown operation: {name}")', '        result = self.operations[name].execute(context)', '        self.history.append(result)', '        return result', '    def rollback(self, name: str, context: OperationContext) -> OperationResult:', '        if name not in self.operations: raise AutomationError(f"unknown operation: {name}")', '        result = self.operations[name].rollback(context)', '        self.history.append(result)', '        return result', '    def report(self) -> dict[str, Any]:', '        return {"operations": len(self.operations), "history": [result.__dict__ for result in self.history]}', '']
    (ROOT / 'automation' / 'automation_engine.py').write_text('\n'.join(out) + '\n', encoding='utf-8')

def make_security() -> None:
    families = {
        'input': ['argv', 'package', 'path', 'url', 'hostname', 'ip', 'port', 'filename', 'workflow', 'plugin', 'theme', 'locale', 'timezone', 'duration', 'size', 'count', 'enum', 'json', 'yaml', 'toml'],
        'scope': ['target', 'cidr', 'domain', 'service', 'port', 'file', 'directory', 'user', 'group', 'process', 'package', 'repository', 'desktop', 'display', 'session', 'workflow', 'job', 'report', 'plugin', 'asset'],
        'policy': ['safe_mode', 'standard_mode', 'advanced_mode', 'lab_mode', 'privilege', 'network', 'filesystem', 'package', 'service', 'desktop', 'backup', 'restore', 'update', 'plugin', 'api', 'scheduler', 'report', 'export', 'import', 'release'],
        'audit': ['chain', 'record', 'timestamp', 'actor', 'consent', 'scope', 'command', 'result', 'error', 'redaction', 'rotation', 'retention', 'export', 'verify', 'signature', 'key', 'checkpoint', 'replay', 'diff', 'integrity'],
        'control': ['consent', 'rate', 'quota', 'timeout', 'cancellation', 'panic', 'lock', 'unlock', 'redaction', 'sandbox', 'isolation', 'resource', 'cpu', 'memory', 'disk', 'network', 'concurrency', 'retry', 'backoff', 'circuit'],
        'identity': ['actor', 'session', 'token', 'api_key', 'certificate', 'signature', 'role', 'permission', 'capability', 'plugin', 'device', 'desktop', 'operator', 'ticket', 'reason', 'approval', 'reviewer', 'owner', 'tenant', 'environment'],
        'integrity': ['hash', 'hmac', 'chain', 'manifest', 'package', 'release', 'update', 'plugin', 'asset', 'shader', 'qml', 'theme', 'database', 'migration', 'backup', 'report', 'workflow', 'scope', 'config', 'secret'],
        'privacy': ['ip', 'hostname', 'username', 'email', 'token', 'secret', 'password', 'cookie', 'header', 'query', 'path', 'command', 'log', 'report', 'backup', 'scope', 'target', 'audit', 'clipboard', 'environment'],
    }
    rules = [(family, name) for family, names in families.items() for name in names]
    out = ['from __future__ import annotations', '', 'import hashlib', 'import ipaddress', 'import json', 'import re', 'import time', 'from dataclasses import dataclass, field', 'from typing import Any', '', 'class SecurityError(ValueError): pass', '', '@dataclass(frozen=True)', 'class SecurityContext:', '    actor: str', '    mode: str = "safe"', '    consent: bool = False', '    targets: frozenset[str] = frozenset()', '    capabilities: frozenset[str] = frozenset()', '    metadata: dict[str, Any] = field(default_factory=dict)', '', '@dataclass(frozen=True)', 'class SecurityDecision:', '    rule: str', '    allowed: bool', '    reason: str', '    risk: str', '    evidence: dict[str, Any]', '', 'class SecurityRule:', '    family = "generic"', '    name = "rule"', '    risk = "low"', '    def evaluate(self, value: Any, context: SecurityContext) -> SecurityDecision:', '        if not context.actor.strip(): return SecurityDecision(self.name, False, "actor required", self.risk, {})', '        return SecurityDecision(self.name, True, "rule passed", self.risk, {"type": type(value).__name__})', '    def enforce(self, value: Any, context: SecurityContext) -> Any:', '        decision = self.evaluate(value, context)', '        if not decision.allowed: raise SecurityError(decision.reason)', '        return value', '    def fingerprint(self, value: Any, context: SecurityContext) -> str:', '        return hashlib.sha256(json.dumps({"rule": self.name, "value": repr(value), "actor": context.actor}, sort_keys=True).encode()).hexdigest()', '']
    for idx, (fam, name) in enumerate(rules):
        cls = ''.join(part.title() for part in name.split('_')) + fam.title() + 'Rule'
        out += [f'class {cls}(SecurityRule):', f'    family = {fam!r}', f'    name = {name!r}', f'    risk = {"high" if idx % 7 == 0 else "medium" if idx % 3 == 0 else "low"!r}', '    def evaluate(self, value: Any, context: SecurityContext) -> SecurityDecision:', '        base = super().evaluate(value, context)', '        if not base.allowed: return base', f'        if {str(fam == "scope")} and str(value) not in context.targets:', '            return SecurityDecision(self.name, False, "value outside declared scope", self.risk, {"value": str(value)})', f'        if {str(fam == "policy")} and context.mode == "safe" and not context.consent:', '            return SecurityDecision(self.name, False, "consent required in safe mode", self.risk, {})', '        return SecurityDecision(self.name, True, "rule passed", self.risk, {"family": self.family, "sequence": '+str(idx)+'})', '']
    out += ['RULES: dict[str, SecurityRule] = {}', '']
    for fam, name in rules:
        cls = ''.join(part.title() for part in name.split('_')) + fam.title() + 'Rule'
        out += [f'RULES[{name!r}] = {cls}()', '']
    out += ['class SecurityEngine:', '    def __init__(self) -> None:', '        self.rules = dict(RULES)', '        self.decisions: list[SecurityDecision] = []', '    def register(self, rule: SecurityRule) -> None:', '        if rule.name in self.rules: raise SecurityError("duplicate rule")', '        self.rules[rule.name] = rule', '    def evaluate(self, name: str, value: Any, context: SecurityContext) -> SecurityDecision:', '        if name not in self.rules: raise SecurityError(f"unknown rule: {name}")', '        decision = self.rules[name].evaluate(value, context)', '        self.decisions.append(decision)', '        return decision', '    def enforce(self, name: str, value: Any, context: SecurityContext) -> Any:', '        return self.rules[name].enforce(value, context)', '    def report(self) -> dict[str, Any]:', '        return {"rules": len(self.rules), "decisions": [decision.__dict__ for decision in self.decisions]}', '']
    (ROOT / 'security' / 'security_engine.py').write_text('\n'.join(out) + '\n', encoding='utf-8')

if __name__ == '__main__':
    make_automation(); make_security()
